

function a(){
    const myError = new Error('exception');
    throw myError;
}

a();